name: planee
description: Planee App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.1.3
  json_annotation: ^4.9.0
  local_push_notifications_module:
    path: ./modules/local_push_notifications
  path: ^1.9.1
  sqflite: ^2.4.2
  very_good_analysis: ^9.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  melos: ^6.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: "Plus Jakarta Sans"
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
